config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    #require title and description
    validates :title, presence: true
    validates :description, presence: true

    #validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        render
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CS3300 Portfolio Project</title>

  </head>
  
  <body>
    <div style="margin: 5% 0 0 10%;">
    <h1>Projects</h1>   
    <h1>CS 3300 Portfolio Project - Fall 2022</h1>

      <div style="padding-left: 2rem;">
        <h4 style="color: blue"> [Jaylen McKinney] </h3>
        

        <!--- Explain what the block of code below this line is doing --->

        <% if user_signed_in? %>
          
          <div> Welcome <%= current_user.email %> </div>
          <button onclick="window.location.href='/projects';">Go to projects</button>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
        
        <% else %>
          <a href="/users/sign_in"> Sign in</a>
        <% end %>

      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300project2022</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Place title here" %>
</div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control", placeholder: "Place description here" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  
  
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<div class="container-fluid bg-primary text-center">
  <h1>Editing Project</h1>
</div>

<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <a href="#" class="navbar-brand mb-0 h1">
      <img class="d-inline-block align-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_n52StbON7o3oaJdq92uDnnvvonKIOUcBIQ&usqp=CAUNavbar"
      width="30" height="30"></img>
  Navbar 
  </a>

  <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item active">
              <a href="http://localhost:3000/projects" class="nav-link active" >Home</a>
          </li>

          <li class="nav-item dropdown">
    
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Signup/Signin</a>
              <div class="dropdown-menu">
                  <a href="http://localhost:3000/users/sign_in" class="dropdown-item">Sign Up</a>
                  <a href="http://localhost:3000/users/sign_in" class="dropdown-item">Sign In</a>
              </div>
          </li>


          
          <li class="nav-item active">
              <a class="nav-link active" href="http://localhost:3000/projects/new">Create Project</a>
          </li>
      </ul>
  </div>
</nav>


<%= render "form", project: @project %>


<br>

<div>
  <%= link_to "Show this project", @project, class: "btn btn-primary" %> |
  <%= link_to "Back to projects", projects_path, class: "btn btn-primary" %>
</div>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>


  <title>Bootstrap 5 Website Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>



</head>

<body>


    <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
        <a href="#" class="navbar-brand mb-0 h1">
            <img class="d-inline-block align-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_n52StbON7o3oaJdq92uDnnvvonKIOUcBIQ&usqp=CAUNavbar"
            width="30" height="30"></img>
        Navbar 
        </a>

        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>

       

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item disabled">
                    <a href="#" class="nav-link disabled" >Home</a>
                </li>

                <li class="nav-item dropdown">
          
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Signup/Signin</a>
                    <div class="dropdown-menu">
                        <a href="http://localhost:3000/users/sign_up" class="dropdown-item">Sign Up</a>
                        <a href="http://localhost:3000/users/sign_in" class="dropdown-item">Sign In</a>
                    </div>
                </li>
    

                
                <li class="nav-item active">
                    <a class="nav-link active" href="http://localhost:3000/projects/new">Create Project</a>
                </li>
            </ul>
        </div>
    </nav>


    <div class="container-fluid bg-primary text-center">
        <h1>My Portfolio</h1>
        <h5> Jaylen McKinney </h5>
    </div>

    <h4>Degree: <a href="https://eas.uccs.edu/cs/academics/undergraduate-programs/bachelor-of-science-in-computer-science" target="_blank">Bachelor of Science in Computer Science</a> </h4>
    <p>
        I am a determined undergrad student currently working towards a B.S. in computer science. 
        Always looking forward to developing my programming skills and working with others to tackle problems. 
        Worked on several class projects that involved intense problem-solving and modularization.
    </p>

    <h5>Programming Languages</h5>
    <ul>
        <li>C++</li>
        <li>C</li>
        <li>Python</li>
        <li>HTML</li>
    </ul>

    <h5>Skills</h5>
    <ul>
        <li>Software Engineering: User stories, unit testing, iterative development, Basic understanding of Docker</li>
        <li>Concepts: Computer architecture, object-oriented programming, modularized coding, command shells</li>
        <li>Personal Attributes: Determination, team player, problem solver</li>
    </ul>


    <div>
        <%= link_to "New project", new_project_path, class: "btn btn-primary"%>
    </div>

    <div class="container" id="projects">
        <% @projects.each do |project| %>
            <div class="row-lg">
                <div class="col-sm">
                    <%= render project %>
                    <p>
                        <%= link_to "Show this project", project, class: "btn btn-primary" %>
                    </p>
                </div>
            </div>
        <% end %>
    </div>


   <!-- <div class="container">
        <div class="row">
            <div class="col-lg">
                <h5>Project 1: T-Shirt Fundraiser Simulation Program - August 2021 - December 2021</h5>
                <ul>
                    <li>Created design documents to outline the different tasks and functions needed to make the code run.</li>
                    <li>Built functions that would validate input, accept payment of the shirts, and calculate the percent of the funds raised that would go to theoretical charity.</li>
                    <li>Modularized code into different functions to accomplish different tasks throughout the semester.</li>
                    <li>Recorded a video describing the code and showing the tasks and pseudocode used for the project.</li>
                <ul>
                <button style="color:red">Show this Project</button>
            </div>

            <div class="col-lg">
                <h5>Project 2: Roman Numeral to Integer - Nov 2021</h5>
                <ul>
                    <li>Used classes to handle converting roman numeral to an integer.</li>
                    <li>Created switch case statements to convert each roman numeral letter into an integer to add to total sum.</li>
                	<li>Defined class member functions in a header file to improve reusability and readability.</li>
                </ul>
                <button style="color:blue">Show this Project</button>
            </div>

            <div class="col-lg">
                <h5>Project 3: Project Assistant at UCCS Cybersecurity Programs Office - Colorado Springs, CO, Sept 2022 - Present</h5>
                <ul>
                    <li>Searching databases to find grant ideas for UCCS.</li>
                	<li>Learning how to use Wix.com to manage school cybersecurity website.</li>
                	<li>Walked children through VR game to teach them more about cybersecurity.</li>
                <ul>
                <button style="color:green">Show this Project</button>
            </div>

        </div>

    </div> -->




</body>

</html>

app/views/projects/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>


<div class="container-fluid bg-primary text-center">
  <h1>New project</h1>
</div>

<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <a href="#" class="navbar-brand mb-0 h1">
      <img class="d-inline-block align-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_n52StbON7o3oaJdq92uDnnvvonKIOUcBIQ&usqp=CAUNavbar"
      width="30" height="30"></img>
  Navbar 
  </a>

  <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item active">
              <a href="http://localhost:3000/projects" class="nav-link active" >Home</a>
          </li>

          <li class="nav-item dropdown">
    
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Signup/Signin</a>
              <div class="dropdown-menu">
                  <a href="http://localhost:3000/users/sign_up" class="dropdown-item">Sign Up</a>
                  <a href="http://localhost:3000/users/sign_in" class="dropdown-item">Sign In</a>
              </div>
          </li>


          
          <li class="nav-item disabled">
              <a class="nav-link disabled" href="#">Create Project</a>
          </li>
      </ul>
  </div>
</nav>


<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path, class: "btn btn-primary" %>
</div>

app/views/projects/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<p style="color: green"><%= notice %></p>

<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <a href="#" class="navbar-brand mb-0 h1">
      <img class="d-inline-block align-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_n52StbON7o3oaJdq92uDnnvvonKIOUcBIQ&usqp=CAUNavbar"
      width="30" height="30"></img>
  Navbar 
  </a>

  <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item active">
              <a href="http://localhost:3000/projects" class="nav-link active" >Home</a>
          </li>

          <li class="nav-item dropdown">
    
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Signup/Signin</a>
              <div class="dropdown-menu">
                  <a href="http://localhost:3000/users/sign_up" class="dropdown-item">Sign Up</a>
                  <a href="http://localhost:3000/users/sign_in" class="dropdown-item">Sign In</a>
              </div>
          </li>


          
          <li class="nav-item active">
              <a class="nav-link active" href="http://localhost:3000/projects/new">Create Project</a>
          </li>
      </ul>
  </div>
</nav>


<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-primary" %> |
  <%= link_to "Back to projects", projects_path, class: "btn btn-primary"%>


  <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-primary" %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>